### PR TITLE
CSS issue

### LINKED ISSUE #4: CSS
# CSS Qualification

| Category | Standard |
| - | - |
| **Task:** | Demonstrate the ability to build a fully responsive website using CSS |
| **Conditions:** | This GitHub repository is downloaded locally and loaded into vs-code. |
| **Standards:** | In the PR style, the HTML webpage using CSS with the following: <ul><li>Style three sections so that they are in a row on desktop, two in a row on top and one on bottom on tablet, and all in a single column on mobile</li><li>Use a media query to style an image to 100% width on mobile and 80% width on desktop</li><li>Style three buttons in a row with padding, margin, border, and box shadow</li><li>On button hover transition the background colors of each button</li><li>Style the page by default is completely hidden. On page load reveal all the content using keyframe animation</li></ul> |

## Notes:
- Create a Pull Request (PR) to this GitHub Repo. 
- Use a naming conventions for CSS class naming (like BEM)

## References
- [Getting to know CSS](https://learn.shayhowe.com/html-css/getting-to-know-css/)
- [Box Model](https://learn.shayhowe.com/html-css/opening-the-box-model/)
- [Backgrounds](https://learn.shayhowe.com/html-css/setting-backgrounds-and-gradients/)
- [Responsive Design](https://learn.shayhowe.com/advanced-html-css/responsive-web-design/)
- [Transitions and Animations](https://learn.shayhowe.com/advanced-html-css/transitions-animations/)

### PR DESCRIPTION
**Pull request by JVSONV**
Created html document that meets CSS issue standards. Fixes #4

### CODE REVIEW

**Comment by vwcBotSchuster** [comment]
The page generally solves the CSS issues. However, it is a completely standalone project. The point of the first week's issues is to design a portfolio and iteratively build towards that. This should build on top of that design as well as on top of the HTML lesson.

**Comment by axecopfire** [comment]
The page generally solves the CSS issues. However, it is a completely standalone project. The point of the first week's issues is to design a portfolio and iteratively build towards that. This should build on top of that design as well as on top of the HTML lesson.

**Comment by JVSONV** [comment]
> 

Ah ok I understand. Unfortunately this is never mentioned in any of the documentation that I have read thus far. If I had know this my HTML document on issue #1 would not have been filled with nonsense like the lorem and headings that where used.

**Comment by axecopfire** [comment]
> > 
> 
> Ah ok I understand. Unfortunately this is never mentioned in any of the documentation that I have read thus far. If I had know this my HTML document on issue #1 would not have been filled with nonsense like the lorem and headings that where used.

This makes sense. We'll work on updating that in the instructions. Thanks for bringing it to my attention.

**Review by axecopfire — APPROVED** [review]

**Comment by Yassin-Aru** [comment]
is there any more issues with the css and htm ...??

**Comment by axecopfire** [comment]
This repo is for students of Vets Who Code. They're currently working through these issues as a part of a course. We are working on a contribution guide to our organization. Thanks for looking to help us out and stay tuned.

**Pull request merged**
